proxy_cache_path /var/cache/nginx/python levels=1:2 keys_zone=python_cache:10m inactive=60s;
proxy_cache_path /var/cache/nginx/go     levels=1:2 keys_zone=go_cache:10m     inactive=120s;

upstream app_python {
    server app-python:8000;
}

upstream app_go {
    server app-go:8080;
}

server {
    listen 80;

    location /python/ {
        proxy_pass http://app_python/;
        proxy_cache python_cache;
        proxy_cache_valid 200 10s;
        proxy_cache_use_stale error timeout updating;
        add_header X-Cache-Status $upstream_cache_status;
    }

    location /go/ {
        proxy_pass http://app_go/;
        proxy_cache go_cache;
        proxy_cache_valid 200 60s;
        proxy_cache_use_stale error timeout updating;
        add_header X-Cache-Status $upstream_cache_status;
    }

    location /stub_status {
        stub_status;
    }
}
